= 4. Tags et versions (Git Tag, Git Checkout Tags)

:revealjs_theme: black
:source-highlighter: highlight.js
:icons: font


== 🔹 Utilisation des Tags

Un tag dans Git est une référence immuable à un commit spécifique. 

=== ...

Il est souvent utilisé pour marquer des versions logicielles.


=== Créer un tag annoté :

git tag -a v1.0 -m "Version 1.0"


=== Lister tous les tags :

git tag

Pousser un tag vers le dépôt distant :

git push origin v1.0

Supprimer un tag localement et sur le dépôt distant :

git tag -d v1.0
git push origin --delete v1.0

=== 🔹 Basculer sur une version spécifique

Si vous souhaitez récupérer une version spécifique marquée par un tag, utilisez :


=== ...

git checkout v1.0

=== ...

Cela met le dépôt en mode détaché (detached HEAD), signifiant que vous ne pouvez pas directement committer sur cette version.

=== ...

Si vous souhaitez modifier le code à partir de cette version :

git checkout -b correctif-v1.0 v1.0

Cela crée une nouvelle branche à partir du tag.

